app1/urls.py
from django.urls import path
from . import views

app_name = "app1"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('empresa/', views.empresa,name='empresa'),
    path('contacto/', views.contacto,name='contacto'),
    path('datos/', views.datos, name='datos'),
    path("map/", views.map, name="map"),
]

formularios/urls.py
from django.urls import path
from . import views

app_name = "formularios"

urlpatterns = [
    path('crear_guitarra', views.crear_guitarra, name='crear_guitarra'),
    path('crear_guitarra_db', views.crear_guitarra_db, name='crear_guitarra_db'),
    path('lista_guitarras', views.lista_guitarras, name='lista_guitarras'),
    path('lista_guitarras_db', views.lista_guitarras_db, name='lista_guitarras_db'),
    path('<identificador>/borrar_guitarra', views.eliminar_guitarra, name='eliminar_guitarra'),
    path('<identificador>/borrar_guitarra_db', views.eliminar_guitarra_db, name='eliminar_guitarra_db'),
    path('<identificador>/editar_guitarra', views.editar_guitarra, name='editar_guitarra'),
    path('<identificador>/editar_guitarra_db', views.editar_guitarra_db, name='editar_guitarra_db'),
    path('graficos/', views.grafico, name='graficos'),
    path('prueba_models/', views.prueba_models, name="prueba_models"),
    path('lista_guitarras_db_cbv', views.ListaGuitarras.as_view(), name='lista_guitarras_db_cbv'),
    path('crear_guitarra_db_cbv', views.CrearGuitarra.as_view(), name='crear_guitarra_db_cbv'),
    path('<pk>/editar_guitarra_db_cbv', views.EditarGuitarra.as_view(), name='editar_guitarra_db_cbv'),
    path('<pk>/borrar_guitarra_db_cbv', views.EliminarGuitarra.as_view(), name='eliminar_guitarra_db_cbv'),
    path('lista_guitarras_db_view', views.ListaGuitarrasView.as_view(), name='lista_guitarras_db_view'),
    path('crear_guitarra_db_view', views.CrearGuitarraView.as_view(), name='crear_guitarra_db_view'),

]

ruta_compuesta/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('tableros_de_datos/', include('app2.urls')),
    path('formularios/', include('formularios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Perfil(models.Model):

    usuario = models.OneToOneField(User, on_delete = models.CASCADE)
    descripcion = models.CharField(max_length=70)
    nacionalidad = models.CharField(max_length=100)
    altura = models.DecimalField(max_digits=4, decimal_places=1)
    peso = models.DecimalField(max_digits=4, decimal_places=1)
    direccion = models.CharField(max_length=300)
    codigo_postal = models.CharField(max_length=20)
    archivo_foto = models.CharField(max_length=400, default="sin asignar")
    rol = models.CharField(max_length=50, default="sin asignar")

    def __str__(self):
        return self.usuario.username + " --> " + self.rol

app1/views.py
import random
import csv

from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required

import uuid
# Create your views here.
def inicio(request):
    print("COOKIES RECIBIDAS: ", request.COOKIES['identificador'])
    lista_nombres=["jhonn","elias","sara conor","blade", "van helsing","freddy", "jason"]
    context = {'temperatura': random.randint(10,32), 'nombres':lista_nombres}
    response = render(request,'app1/index.html', context)
    if not ('identificador' in request.COOKIES.keys()):
        max_age = 365 * 24 * 60 * 60  # 1 Año
        response.set_cookie(
                        key="identificador", 
                        value=uuid.uuid4(), 
                        max_age=max_age
                        )
    return response

@login_required(login_url="/accounts/login/")
def empresa(request):
    context = {'temperatura': random.randint(10,32)}
    return render(request,'app1/empresa.html', context)

def contacto(request):
    context = {'temperatura': random.randint(10,32)}
    return render(request,'app1/contacto.html', context)

def datos(request):
    filename = '/app1/data/iris.csv'
    ruta_completa_archivo = str(settings.BASE_DIR)+filename
    with open(ruta_completa_archivo, 'r') as archivo:
        data = csv.DictReader(archivo)
        data_list = []
        for elemento in data:
            data_list.append(elemento)
    context = {'datos_desde_archivo': data_list}
    print(dict(request.session))
    if 'num_visitas' not in request.session:
        request.session['num_visitas']= 1
    else:
        request.session['num_visitas'] += 1
    context['num_visitas']=request.session['num_visitas']
    return render(request, 'app1/datos.html', context)



def map(request):
    return render(request, 'app1/map.html')

app1/templates/app1/contacto.html
{% extends "base.html" %}

{% block contenidos %}
<h3>Hola, estamos en contacto</h3>
{% endblock %}

app1/templates/app1/datos.html
{% extends "base.html" %}

{% block contenidos %}
<h3>Página de Datos de Flores Iris</h3>
<h2>Usted ha venido {{num_visitas}} veces a nuestro sitio!</h2>
{% for registro in datos_desde_archivo %}
<hr>
<p>{{registro}}</p>
<p>{{registro.sepal_length}}</p>
<p>{{registro.sepal_width}}</p>
<p>{{registro.petal_length}}</p>
<p>{{registro.petal.width}}</p>
<p>{{registro.species}}</p>
{% endfor %}

{% endblock %}

app1/templates/app1/empresa.html
{% extends "base.html" %}

{% block contenidos %}
<h3>Hola, estamos en empresa</h3>
{% endblock %}

app1/templates/app1/index.html
{% extends "base.html" %}

{% load static %}
{% block contenidos %}

    <h1>Bienvenido a nuestra pagina de inicio!</h1>

    <img src="{% static 'app1/img/foto.jpg' %}" alt="foto" width="30%">

    <h3>{{temperatura}}</h3>

    {% for nombre in nombres %}
    <h4>{{nombre}}</h4>
    {% endfor %}

    {# si quisiera incorporar otros fragmentos de html hacemos lo siguiente#}
    {% comment %}
    {% if condicion %}
       {% include "app1/widget_del_tiempo.html" %}
    {% else %}
        {% include "app1/widget_de_datos.html" %}
    {% endif %}
    {% endcomment %}

{% endblock %}

app1/templates/app1/map.html
{% extends "base.html" %}

{% load static %}
{% block contenidos %}

    <h1>Página de Enlaces del Sistema</h1>
    <p><b>Ruta actual:</b> {{ request.path }}</p>
    {% if user.is_authenticated %}
    <p><b>Usuario Id:</b> {{user.id}}<br><b>Username:</b> {{ user.username }}<br><b>Email:</b> {{ user.email }}<br><b>Rol en la aplicación:</b> {{ user.perfil.rol }}</p><br>
    <p><a href="{% url 'logout' %}?next={% url 'app1:map' %}">
			{{request.get_host}}{% url 'logout' %}?next={% url 'app1:map' %}</a></p>
    {% else %}
    <p><a href="{% url 'login' %}?next={{ request.path }}">
			{{request.get_host}}{% url 'login' %}?next={{ request.path }}</a> Autentica y vuelve a esta página</p>
    {% endif %}
    <h3>Nuestras secciones:</h3>
    <ul>
        <li><p><a href="{% url 'app1:inicio' %}">{{request.get_host }}{% url 'app1:inicio' %}</a>: 
                <br>Página de Inicio -- No requiere autenticación</p></li>
        <li><p><a href="{% url 'formularios:lista_guitarras_db_cbv' %}">{{request.get_host }}{% url 'formularios:lista_guitarras_db_cbv' %}</a>: 
                <br>Página Lista Guitarras DB CBV-- Requiere autenticación (LoginRequiredMixin) </p></li>
        <li><p><a href="{% url 'formularios:crear_guitarra_db_cbv' %}">{{request.get_host }}{% url 'formularios:crear_guitarra_db_cbv' %}</a>: 
                <br>Página Crear Guitarras DB CBV -- Requiere Autenticación y Permiso (LoginRequiredMixin, UserPassesTestMixin)</p></li>
        <li><p><a href="{% url 'app1:empresa' %}">{{request.get_host }}{% url 'app1:empresa' %}</a>: 
                <br>Descripción de Empresa -- Requiere autenticación (@login_required)</p></li>
        <li><p><a href="{% url 'app1:datos' %}">{{request.get_host }}{% url 'app1:datos' %}</a>:
                <br>Página de Datos-- No requiere autenticación</p></li>
        <li><p><a href="{% url 'formularios:prueba_models' %}">{{request.get_host }}{% url 'formularios:prueba_models' %}</a>:
                <br>Página de Prueba Models-- Requiere autenticación (user.is_authenticated)</p></li>
        <li><p><a href="{% url 'formularios:crear_guitarra' %}">{{request.get_host }}{% url 'formularios:crear_guitarra' %}</a>: 
                <br>Página Crear Guitarras -- Requiere Autenticación y permiso (@login_required, )</p></li>

        </ul>

{% endblock %}