app1/urls.py
from django.urls import path
from . import views

app_name = "app1"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('empresa/', views.empresa,name='empresa'),
    path('contacto/', views.contacto,name='contacto'),
    path('datos/', views.datos, name='datos'),
    path("map/", views.map, name="map"),
]

app2/urls.py
from django.urls import path
from . import views

app_name = "app2"

urlpatterns = [
    path('principal/', views.principal,name='principal'),
]

formularios/urls.py
from django.urls import path
from . import views

app_name = "formularios"

urlpatterns = [
    path('crear_guitarra', views.crear_guitarra, name='crear_guitarra'),
    path('crear_guitarra_db', views.crear_guitarra_db, name='crear_guitarra_db'),
    path('lista_guitarras', views.lista_guitarras, name='lista_guitarras'),
    path('lista_guitarras_db', views.lista_guitarras_db, name='lista_guitarras_db'),
    path('<identificador>/borrar_guitarra', views.eliminar_guitarra, name='eliminar_guitarra'),
    path('<identificador>/borrar_guitarra_db', views.eliminar_guitarra_db, name='eliminar_guitarra_db'),
    path('<identificador>/editar_guitarra', views.editar_guitarra, name='editar_guitarra'),
    path('<identificador>/editar_guitarra_db', views.editar_guitarra_db, name='editar_guitarra_db'),
    path('graficos/', views.grafico, name='graficos'),
    path('prueba_models/', views.prueba_models, name="prueba_models"),
    path('lista_guitarras_db_cbv', views.ListaGuitarras.as_view(), name='lista_guitarras_db_cbv'),
    path('crear_guitarra_db_cbv', views.CrearGuitarra.as_view(), name='crear_guitarra_db_cbv'),
    path('<pk>/editar_guitarra_db_cbv', views.EditarGuitarra.as_view(), name='editar_guitarra_db_cbv'),
    path('<pk>/borrar_guitarra_db_cbv', views.EliminarGuitarra.as_view(), name='eliminar_guitarra_db_cbv'),
    path('lista_guitarras_db_view', views.ListaGuitarrasView.as_view(), name='lista_guitarras_db_view'),
    path('crear_guitarra_db_view', views.CrearGuitarraView.as_view(), name='crear_guitarra_db_view'),

]

ruta_compuesta/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('tableros_de_datos/', include('app2.urls')),
    path('formularios/', include('formularios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Loading Bootstrap CSS -->
    <link 
    rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
    crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" 
        rel="stylesheet" type="text/css">
    <link href="{% static 'app1/css/style.css' %}" rel="stylesheet" >
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <a class="navbar-brand" href="#">Django</a>
  
        <!-- Navigation Bar Hamburger-->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
          aria-expanded="false"
          aria-controls="navigation" 
          aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- End Navigation Bar Hamburger -->
        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navigation">
           <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a
                  href="#"
                  class="nav-link dropdown-toggle"
                  data-toggle="dropdown"
                  role="button"
                  aria-haspopup="true"
                  aria-expanded="false">
                      General <span class="caret"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'app1:inicio' %}">
                    Inicio
                  </a>
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'app1:empresa' %}">
                    Empresa
                  </a>
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'app1:contacto' %}">
                    Contacto
                  </a>
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'app1:datos' %}"> 
                    Datos Iris
                  </a>
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'app2:principal' %}">
                    Dashboard Principal
                  </a>
                  <a class="dropdown-item scroll-trigger"
                  href="{% url 'formularios:graficos' %}">
                    Graficos
                  </a>
              </div>
          
              <li class="nav-item dropdown">
                <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false">
                        Guitarras Json <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item scroll-trigger"
                      href="{% url 'formularios:lista_guitarras' %}">
                        Lista Guitarras Json
                    </a>
                    <a class="dropdown-item scroll-trigger"
                    href="{% url 'formularios:crear_guitarra' %}">
                        Crear Guitarra Json
                    </a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false">
                        Guitarras DB <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item scroll-trigger"
                      href="{% url 'formularios:lista_guitarras_db' %}">
                        Lista Guitarras DB
                    </a>
                    <a class="dropdown-item scroll-trigger"
                    href="{% url 'formularios:crear_guitarra_db' %}">
                        Crear Guitarra DB
                    </a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a
                    href="#"
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false">
                        Guitarras DB CBV <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item scroll-trigger"
                      href="{% url 'formularios:lista_guitarras_db_cbv' %}">
                        Lista Guitarras DB CBV
                    </a>
                    <a class="dropdown-item scroll-trigger"
                    href="{% url 'formularios:crear_guitarra_db_cbv' %}">
                        Crear Guitarra DB CBV
                    </a>
                </div>
              </li>
            <li class="nav-item">
              <a
                class="nav-link scroll-trigger" 
                href="{% url 'app1:map' %}">
                  Map
              </a>
            </li>
           </ul>

        </div>
        <!-- Navigation Links -->
    </nav>
    <!-- End Navigation Bar -->



    <!-- Section: Contacto -->
    <div class="" id="base">
        <div class="row">
            <div class="col-12">
            {% block contenidos %}{% endblock %}
            </div>
        </div>
 
    </div>
    <!-- End Section: Contacto -->


    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script 
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
      crossorigin="anonymous">
    </script>
    <script 
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
      crossorigin="anonymous">
    </script>
    <script 
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" 
      crossorigin="anonymous">
    </script>
</body>
</html>