app1/urls.py
from django.urls import path
from . import views

app_name = "app1"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('empresa/', views.empresa,name='empresa'),
    path('contacto/', views.contacto,name='contacto'),
    path('datos/', views.datos, name='datos'),
    path("map/", views.map, name="map"),
]

formularios/urls.py
from django.urls import path
from . import views

app_name = "formularios"

urlpatterns = [
    path('crear_guitarra', views.crear_guitarra, name='crear_guitarra'),
    path('crear_guitarra_db', views.crear_guitarra_db, name='crear_guitarra_db'),
    path('lista_guitarras', views.lista_guitarras, name='lista_guitarras'),
    path('lista_guitarras_db', views.lista_guitarras_db, name='lista_guitarras_db'),
    path('<identificador>/borrar_guitarra', views.eliminar_guitarra, name='eliminar_guitarra'),
    path('<identificador>/borrar_guitarra_db', views.eliminar_guitarra_db, name='eliminar_guitarra_db'),
    path('<identificador>/editar_guitarra', views.editar_guitarra, name='editar_guitarra'),
    path('<identificador>/editar_guitarra_db', views.editar_guitarra_db, name='editar_guitarra_db'),
    path('graficos/', views.grafico, name='graficos'),
    path('prueba_models/', views.prueba_models, name="prueba_models"),
    path('lista_guitarras_db_cbv', views.ListaGuitarras.as_view(), name='lista_guitarras_db_cbv'),
    path('crear_guitarra_db_cbv', views.CrearGuitarra.as_view(), name='crear_guitarra_db_cbv'),
    path('<pk>/editar_guitarra_db_cbv', views.EditarGuitarra.as_view(), name='editar_guitarra_db_cbv'),
    path('<pk>/borrar_guitarra_db_cbv', views.EliminarGuitarra.as_view(), name='eliminar_guitarra_db_cbv'),
    path('lista_guitarras_db_view', views.ListaGuitarrasView.as_view(), name='lista_guitarras_db_view'),
    path('crear_guitarra_db_view', views.CrearGuitarraView.as_view(), name='crear_guitarra_db_view'),

]

ruta_compuesta/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('tableros_de_datos/', include('app2.urls')),
    path('formularios/', include('formularios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

formularios/models.py
import datetime
from django.db import models
from django.core import validators
from django.core.exceptions import ValidationError


def validar_fecha(fecha):
    fecha_menor = datetime.datetime.strptime("2020-12-01", "%Y-%m-%d").date()
    fecha_mayor = datetime.datetime.strptime("2020-12-31", "%Y-%m-%d").date()
    if fecha_menor <= fecha <= fecha_mayor:
        return fecha
    else:
        raise ValidationError("Sólo acepta fechas de diciembre 2020")


# Create your models here.

class Musico(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    pais = models.CharField(max_length=50, default="Chile")

class Guitarra(models.Model):
    marca = models.CharField(max_length=80)
    modelo = models.CharField(max_length=80)
    cuerdas = models.IntegerField()
    madera = models.CharField(max_length=50, default="No informada")
    fecha_compra = models.DateField()
    musico = models.ForeignKey(Musico, on_delete=models.CASCADE)

class Banda(models.Model):
    nombre = models.CharField(max_length=50)
    fecha_formacion = models.DateField()
    musicos = models.ManyToManyField(Musico)

'''
class pasaporte(models.Model):
    numero = models.IntegerField()
    musico = models.OneToOneField(Musico, on_delete=models.CASCADE)

'''

# Modelo de Guitarra para vistas basadas en clases (CBV)

class GuitarraCBV(models.Model):
    marca = models.CharField(max_length=80,
                validators = [ 
                        validators.MinLengthValidator( 3, 
						    "La marca no puede ser de menos de 3 letras"),
                        validators.MaxLengthValidator( 10, 
						    "La marca no puede ser de más de 10 letras") ]
                )
    modelo = models.CharField(max_length=80,
                validators = [ 
                        validators.MinLengthValidator( 3, 
						    "El modelo no puede ser de menos de 3 letras"),
                        validators.MaxLengthValidator( 30, 
						    "El modelo no puede ser de más de 30 letras") ]
                )
    cuerdas = models.IntegerField(
                validators = [ 
                        validators.MinValueValidator( 6, 
						    "No pueden ser menos de 6 cuerdas"),
                        validators.MaxValueValidator( 12, 
						    "No pueden ser más de 12 cuerdas") ]
                )
    madera = models.CharField(max_length=50, default="No informada")
    fecha_compra = models.DateField(validators = [validar_fecha])

formularios/forms.py
import datetime

from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from .models import GuitarraCBV

def validar_fecha(fecha):
    fecha_menor = datetime.datetime.strptime("2020-12-01", "%Y-%m-%d").date()
    fecha_mayor = datetime.datetime.strptime("2020-12-31", "%Y-%m-%d").date()
    if fecha_menor <= fecha <= fecha_mayor:
        return fecha
    else:
        raise ValidationError("Sólo acepta fechas de diciembre 2020")


class FormularioGuitarra(forms.Form):
    marca = forms.CharField(
                validators = [ 
                        validators.MinLengthValidator( 3, 
						    "La marca no puede ser de menos de 3 letras"),
                        validators.MaxLengthValidator( 10, 
						    "La marca no puede ser de más de 10 letras") ])   
    modelo = forms.CharField(
                validators = [ 
                        validators.MinLengthValidator( 3, 
						    "El modelo no puede ser de menos de 3 letras"),
                        validators.MaxLengthValidator( 30, 
						    "El modelo no puede ser de más de 30 letras") ])
    cuerdas = forms.IntegerField(validators = [ 
                        validators.MinValueValidator( 6, 
						    "No pueden ser menos de 6 cuerdas"),
                        validators.MaxValueValidator( 12, 
						    "No pueden ser más de 12 cuerdas") ])
    fecha_compra = forms.DateField(validators = [validar_fecha])


# Formulario para vistas basadas en clases (CBV)

class FormularioGuitarraCBV(forms.ModelForm):

    class Meta:
        model = GuitarraCBV
        fields='__all__'

formularios/views.py
import json
import datetime

from django.shortcuts import render, redirect
from .forms import FormularioGuitarra
from django.conf import settings
from django.urls import reverse_lazy
from .models import Guitarra, Musico, GuitarraCBV
from django.views.generic import ListView
from django.views.generic.edit import CreateView ,UpdateView, DeleteView
from django.views.generic.base import View
# esto es para poder enviar mensajes entre views
from django.contrib import messages 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

def context_lista_guitarras():
    filename= "/formularios/data/guitarras.json"
    with open(str(settings.BASE_DIR)+filename, 'r') as file:
        guitarras=json.load(file)
    
    # ordenar con funcion convencional
    def criterio_ordenamiento(diccionario):
        return diccionario['identificador']
    guitarras['guitarras'] = sorted(guitarras['guitarras'], key=criterio_ordenamiento)
    '''
    # ordenar con lambda function
    guitarras['guitarras'] = sorted(guitarras['guitarras'], key=lambda k: k['identificador'])
    '''
    print(guitarras['guitarras'])
    context = {'lista_guitarras': guitarras['guitarras']}
    return context

# Create your views here.

# C de CRUD con archivo JSON



def funcion_permiso(user):
    return user.perfil.rol=="medico"

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
@login_required(login_url="/accounts/login/")
@user_passes_test(funcion_permiso)
def crear_guitarra(request):

    if request.method == "GET":
        formulario = FormularioGuitarra()
        context = {'formulario': formulario}
        context.update(context_lista_guitarras())
        print(context)
        return render(request, 'formularios/crear_guitarra.html', context)

    elif request.method == "POST":
        print("El POST contiene:", request.POST)

        formulario_devuelto = FormularioGuitarra(request.POST)

        if formulario_devuelto.is_valid() == True:
            datos_formulario = formulario_devuelto.cleaned_data
            datos_formulario['fecha_compra']=datos_formulario['fecha_compra'].strftime("%Y-%m-%d")
            print("Los datos limpios del formulario son:", datos_formulario)
            filename= "/formularios/data/guitarras.json"
            with open(str(settings.BASE_DIR)+filename, 'r') as file:
                data=json.load(file)
                nuevo_ultimo_identificador = int(data['ultimo_identificador']) + 1
                data['ultimo_identificador'] = nuevo_ultimo_identificador
                datos_formulario['identificador'] = nuevo_ultimo_identificador
                data['guitarras'].append(datos_formulario)
            with open(str(settings.BASE_DIR)+filename, 'w') as file:
                json.dump(data, file)
            
            return redirect('formularios:crear_guitarra')
        else:
            context = {'formulario': formulario_devuelto}
            context.update(context_lista_guitarras())
            return render(request, 'formularios/crear_guitarra.html', context)


# R de CRUD con archivo JSON
def lista_guitarras(request):
    context = context_lista_guitarras()
    return render(request, 'formularios/lista_guitarras.html', context)

# U de CRUD con archivo JSON
def editar_guitarra(request, identificador):

    if request.method == "GET":
        filename= "/formularios/data/guitarras.json"
        with open(str(settings.BASE_DIR)+filename, 'r') as file:
            data=json.load(file)
        for guitarra in data['guitarras']:
            if int(guitarra['identificador'])==int(identificador):
                break
        formulario = FormularioGuitarra(initial=guitarra)
        context = {'formulario': formulario, 'identificador': identificador}
        return render(request, 'formularios/editar_guitarra.html', context)

    elif request.method == "POST":
        print("El POST contiene:", request.POST)
        formulario_devuelto = FormularioGuitarra(request.POST)
        if formulario_devuelto.is_valid() == True:
            datos_formulario = formulario_devuelto.cleaned_data
            datos_formulario['fecha_compra']=datos_formulario['fecha_compra'].strftime("%Y-%m-%d")
            filename= "/formularios/data/guitarras.json"
            with open(str(settings.BASE_DIR)+filename, 'r') as file:
                data=json.load(file)
            for guitarra in data['guitarras']:
                if int(guitarra['identificador'])==int(identificador):
                    data['guitarras'].remove(guitarra)
                    datos_formulario['identificador'] = guitarra['identificador']
                    data['guitarras'].append(datos_formulario)
                    break
            with open(str(settings.BASE_DIR)+filename, 'w') as file:
                json.dump(data, file)
            return redirect('formularios:lista_guitarras')
        else:
            context = {'formulario': formulario_devuelto}
            return render(request, 'formularios/editar_guitarra.html', context)


# D de CRUD con archivo JSON
def eliminar_guitarra(request, identificador):

    if request.method == "GET":
        context = {'identificador': identificador}
        return render(request, "formularios/eliminar_guitarra.html", context)

    if request.method == "POST":
        filename= "/formularios/data/guitarras.json"
        with open(str(settings.BASE_DIR)+filename, 'r') as file:
            data=json.load(file)
        for guitarra in data['guitarras']:
            if int(guitarra['identificador'])==int(identificador):
                data['guitarras'].remove(guitarra)
                break
        with open(str(settings.BASE_DIR)+filename, 'w') as file:
            json.dump(data, file)
        
        return redirect('formularios:lista_guitarras')



# C de CRUD con Base de Datos

def crear_guitarra_db(request):

    if request.method == "GET":
        formulario = FormularioGuitarra()
        guitarras = Guitarra.objects.all()
        context = { 'formulario': formulario, 
                    'lista_guitarras': guitarras}
        return render(request, 'formularios/crear_guitarra_db.html', context)

    elif request.method == "POST":
        print("El POST contiene:", request.POST)

        formulario_devuelto = FormularioGuitarra(request.POST)

        if formulario_devuelto.is_valid() == True:
            datos_formulario = formulario_devuelto.cleaned_data
            datos_formulario['fecha_compra']=datos_formulario['fecha_compra'].strftime("%Y-%m-%d")
            print("Los datos limpios del formulario son:", datos_formulario)
            Guitarra.objects.create(
                            modelo=datos_formulario['modelo'],
                            marca=datos_formulario['marca'],
                            cuerdas=datos_formulario['cuerdas'],
                            fecha_compra=datos_formulario['fecha_compra'],
                            madera="estandar",
                            musico=Musico.objects.all()[0]
                            )
            return redirect('formularios:crear_guitarra_db')
        else:
            context = {'formulario': formulario_devuelto}
            context.update(context_lista_guitarras())
            return render(request, 'formularios/crear_guitarra_db.html', context)


# R de CRUD con Base de Datos
def lista_guitarras_db(request):
    guitarras = Guitarra.objects.all().order_by("id")
    context = { 'lista_guitarras': guitarras}
    return render(request, 'formularios/lista_guitarras_db.html', context)


# U de CRUD con Base de Datos
def editar_guitarra_db(request, identificador):

    if request.method == "GET":
        guitarra = Guitarra.objects.filter(id=identificador).values()[0]
        formulario = FormularioGuitarra(initial=guitarra)
        context = {'formulario': formulario, 'identificador': identificador}
        return render(request, 'formularios/editar_guitarra_db.html', context)

    elif request.method == "POST":
        print("El POST contiene:", request.POST)
        formulario_devuelto = FormularioGuitarra(request.POST)
        if formulario_devuelto.is_valid() == True:
            datos_formulario = formulario_devuelto.cleaned_data
            datos_formulario['fecha_compra']=datos_formulario['fecha_compra'].strftime("%Y-%m-%d")
            guitarra = Guitarra.objects.filter(id=identificador).update(
                            modelo=datos_formulario['modelo'],
                            marca=datos_formulario['marca'],
                            cuerdas=datos_formulario['cuerdas'],
                            fecha_compra=datos_formulario['fecha_compra']
                            )
            return redirect('formularios:lista_guitarras_db')
        else:
            context = {'formulario': formulario_devuelto}
            return render(request, 'formularios/editar_guitarra_db.html', context)


# D de CRUD con Base de Datos
def eliminar_guitarra_db(request, identificador):

    if request.method == "GET":
        context = {'identificador': identificador}
        return render(request, "formularios/eliminar_guitarra_db.html", context)

    if request.method == "POST":
        Guitarra.objects.filter(id=identificador).delete()
        return redirect('formularios:lista_guitarras_db')



# CRUD con Vistas en Base a Clases (CBV)

def verificar_que_es_medico(user):
    return user.perfil.rol=="medico"

# C de CRUD
class CrearGuitarra(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = GuitarraCBV
    fields = '__all__'
    template_name = 'formularios/crear_guitarra_db_cbv.html'
    success_url = reverse_lazy('formularios:lista_guitarras_db_cbv')

    def test_func(self):
        return verificar_que_es_medico(self.request.user)

# R de CRUD
class ListaGuitarras(LoginRequiredMixin, ListView):
    model = GuitarraCBV
    context_object_name='guitarras'
    template_name = 'formularios/lista_guitarras_db_cbv.html'

formularios/templates/formularios/crear_guitarra.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Pagina Crear Guitarras</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{formulario.as_table}}
    </table>
    <input type="hidden" name="elemento" value="guitarra">
    <input type="submit" value="Crear">
</form>
<hr>
    <!-- Section: Competencias -->
    <div class="container-fluid bg-dark" id="lista-guitarras">
        <div class="row">
            <h3>Listado de Guitarras Actuales</h3>
        </div>
        <div class="row">
            {% for guitarra in lista_guitarras %}
            <div class="col-md-6 col-lg-3">
                <div class="card">
                    <h3 class="card-header">Guitarra N° {{guitarra.identificador}}</h3>
                    <div class="card-body">
                        <h4 class="card-title">{{guitarra.marca}}</h4>
                        <p class="card-text">{{guitarra.modelo}}</p>
                        <p class="card-text">{{guitarra.cuerdas}}</p>
                        <p class="card-text">{{guitarra.fecha_compra}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End Section: Competencias -->
{% endblock %}

formularios/templates/formularios/crear_guitarra_db.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Pagina Crear Guitarras con DB</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{formulario.as_table}}
    </table>
    <input type="hidden" name="elemento" value="guitarra">
    <input type="submit" value="Crear">
</form>
<hr>
    <!-- Section: Competencias -->
    <div class="container-fluid bg-dark" id="lista-guitarras">
        <div class="row">
            <h3>Listado de Guitarras Actuales</h3>
        </div>
        <div class="row">
            {% for guitarra in lista_guitarras %}
            <div class="col-md-6 col-lg-3">
                <div class="card">
                    <h3 class="card-header">Guitarra N° {{guitarra.id}}</h3>
                    <div class="card-body">
                        <h4 class="card-title">{{guitarra.marca}}</h4>
                        <p class="card-text">{{guitarra.modelo}}</p>
                        <p class="card-text">{{guitarra.cuerdas}}</p>
                        <p class="card-text">{{guitarra.fecha_compra}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End Section: Competencias -->
{% endblock %}

formularios/templates/formularios/crear_guitarra_db_cbv.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Pagina Crear Guitarras con DB CBV</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="hidden" name="elemento" value="guitarra">
    <input type="submit" value="Crear">
</form>

{% endblock %}

formularios/templates/formularios/crear_guitarra_db_view.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Pagina Crear Guitarras con DB y clase View</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{formulario.as_table}}
    </table>
    <input type="hidden" name="elemento" value="guitarra">
    <input type="submit" value="Crear">
</form>
<hr>
    <!-- Section: Competencias -->
    <div class="container-fluid bg-dark" id="lista-guitarras">
        <div class="row">
            <h3>Listado de Guitarras Actuales</h3>
        </div>
        <div class="row">
            {% for guitarra in lista_guitarras %}
            <div class="col-md-6 col-lg-3">
                <div class="card">
                    <h3 class="card-header">Guitarra N° {{guitarra.id}}</h3>
                    <div class="card-body">
                        <h4 class="card-title">{{guitarra.marca}}</h4>
                        <p class="card-text">{{guitarra.modelo}}</p>
                        <p class="card-text">{{guitarra.cuerdas}}</p>
                        <p class="card-text">{{guitarra.fecha_compra}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End Section: Competencias -->
{% endblock %}

formularios/templates/formularios/editar_guitarra_db.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Editando Guitarra ID: {{identificador}}</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{formulario.as_table}}
    </table>
    <input type="submit" value="Editar">
    <a href="{% url 'formularios:lista_guitarras_db' %}"><input type="button" value="Cancelar"></a>
</form>

{% endblock %}

formularios/templates/formularios/editar_guitarra_db_cbv.html
{% extends "base.html" %}

{% block contenidos %}

<h1>Pagina Editar Guitarras con DB CBV</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="hidden" name="elemento" value="guitarra">
    <input type="submit" value="Guardar">
</form>

{% endblock %}

formularios/templates/formularios/eliminar_guitarra.html
{% extends "base.html" %}

{% block contenidos %}

<form action="{% url 'formularios:eliminar_guitarra' identificador=identificador %}" method="POST">
    {% csrf_token %}
    Está seguro de eliminar la guitarra con Identificador = {{identificador}}?
    <input type="submit" value="Sí">
</form>


{% endblock %}

formularios/templates/formularios/eliminar_guitarra_db.html
{% extends "base.html" %}

{% block contenidos %}

<form action="{% url 'formularios:eliminar_guitarra_db' identificador=identificador %}" method="POST">
    {% csrf_token %}
    Está seguro de eliminar en la DB la guitarra con Id = {{identificador}}?
    <input type="submit" value="Sí">
</form>


{% endblock %}

formularios/templates/formularios/eliminar_guitarra_db_cbv.html
{% extends "base.html" %}

{% block contenidos %}

<form action="{% url 'formularios:eliminar_guitarra_db_cbv' pk=guitarra.id %}" method="POST">
    {% csrf_token %}
    Está seguro de eliminar en la DB la guitarra con Id = {{guitarra.id}}?
    <input type="submit" value="Sí">
</form>


{% endblock %}

formularios/templates/formularios/graficos.html
{% extends "base.html" %}

{% block contenidos %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
        <style>
            .chart {
                width:40%;
            }
        </style>
<!-- Se crea el grafico y se asigna ancho y alto -->
<div class="chart">
    <canvas id="barra"></canvas>
</div>  

<div class="chart">
    <canvas id="pie"></canvas>
</div>
</body>
<script>
var ctx= document.getElementById("barra");
var barra= new Chart(ctx,{

    /* En type se define el tipo de grafico a mostrar */

    type:"bar",
    data:{
        labels:{{modelos|safe}},
        datasets:[{
                label:'Grafico Tipo Barra',
                data:{{cuerdas|safe}},
                backgroundColor:[

                    /* Se define el color en formato RGB por cada barra */

                    'rgb(51, 255, 62)',
                    'rgb(51, 93, 255)',
                    'rgb(207, 40, 52)',
                    'rgb(116, 51, 255)',
                    'rgb(51, 212, 255)'
                ]
        }]
    },
    options:{
        scales:{
            yAxes:[{
                    ticks:{
                        beginAtZero:true
                    }
            }]
        }
    }
});

var ctx = document.getElementById("pie");
var pie = new Chart(ctx,{

    /* En type se define el tipo de grafico a mostrar */

    type:"pie",
    data:{
        labels:{{modelos|safe}},
        datasets:[{
                label:'Cuerdas',
                data:{{cuerdas|safe}},
                backgroundColor:[

                    /* Se define el color en formato RGB por cada barra */

                    'rgb(51, 255, 62)',
                    'rgb(51, 93, 255)',
                    'rgb(207, 40, 52)',
                    'rgb(116, 51, 255)',
                    'rgb(51, 212, 255)'
                ]
        }]
    },
  
});
</script>
{% endblock %}

formularios/templates/formularios/lista_guitarras.html
{% extends "base.html" %}

{% block contenidos %}

<!-- Section: Guitarras -->
<div class="container-fluid bg-dark" id="lista-guitarras">
    <div class="row">
        <h3>Listado de Guitarras Actuales</h3>
    </div>
    <div class="row">
        <div class="col-12">
            <p class="btn btn-light"><a href="{% url 'formularios:crear_guitarra' %}">Crear Nueva Guitarra</a></p>
        </div>
    </div>
    <div class="row">
        {% for guitarra in lista_guitarras %}
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <h3 class="card-header">Guitarra N° {{guitarra.identificador}}</h3>
                <div class="card-body">
                    <h4 class="card-title">{{guitarra.marca}}</h4>
                    <p class="card-text">{{guitarra.modelo}}</p>
                    <p class="card-text">{{guitarra.cuerdas}}</p>
                    <p class="card-text">{{guitarra.fecha_compra}}</p>
                    <a href="{% url 'formularios:eliminar_guitarra' identificador=guitarra.identificador %}" class="btn btn-dark">Borrar</a>
                    <a href="{% url 'formularios:editar_guitarra' identificador=guitarra.identificador %}" class="btn btn-dark">Editar</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- End Section: Guitarras -->

{% endblock %}

formularios/templates/formularios/lista_guitarras_db_cbv.html
{% extends "base.html" %}

{% block contenidos %}

<!-- Section: Guitarras -->
<div class="container-fluid bg-dark" id="lista-guitarras">
    <div class="row">
        <h3>Listado de Guitarras Actuales en DB</h3>
    </div>
    <div class="row">
        <div class="col-12">
            <p class="btn btn-light"><a href="{% url 'formularios:crear_guitarra_db_cbv' %}">Crear Nueva Guitarra</a></p>
        </div>
    </div>
    <div class="row">
        {% for guitarra in guitarras %}
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <h3 class="card-header">Guitarra N° {{guitarra.id}}</h3>
                <div class="card-body">
                    <h4 class="card-title">{{guitarra.marca}}</h4>
                    <p class="card-text">{{guitarra.modelo}}</p>
                    <p class="card-text">{{guitarra.cuerdas}}</p>
                    <p  class="card-text">{{guitarra.madera}}</p>
                    <p class="card-text">{{guitarra.fecha_compra}}</p>
                    <a href="{% url 'formularios:editar_guitarra_db_cbv' pk=guitarra.id %}" class="btn btn-dark">Editar</a>
                    <a href="{% url 'formularios:eliminar_guitarra_db_cbv' pk=guitarra.id %}" class="btn btn-dark">Eliminar</a>
                
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- End Section: Guitarras -->

{% endblock %}

formularios/templates/formularios/lista_guitarras_db_view.html
{% extends "base.html" %}

{% block contenidos %}

<!-- Section: Guitarras -->
<div class="container-fluid bg-dark" id="lista-guitarras">+
    {% if messages %}
    <div class="row" id="mensaje">
        {% for mensaje in messages %}
        <div class="col-12">
        <p>{{mensaje}}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="row">
        <h3>Listado de Guitarras Actuales en DB con clase View</h3>
    </div>
    <div class="row">
        <div class="col-12">
            <p class="btn btn-light"><a href="{% url 'formularios:crear_guitarra_db_view' %}">Crear Nueva Guitarra</a></p>
        </div>
    </div>
    <div class="row">
        {% for guitarra in guitarras %}
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <h3 class="card-header">Guitarra N° {{guitarra.id}}</h3>
                <div class="card-body">
                    <h4 class="card-title">{{guitarra.marca}}</h4>
                    <p class="card-text">{{guitarra.modelo}}</p>
                    <p class="card-text">{{guitarra.cuerdas}}</p>
                    <p class="card-text">{{guitarra.fecha_compra}}</p>
                    <a href="" class="btn btn-dark">Borrar</a>
                    <a href="" class="btn btn-dark">Editar</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- End Section: Guitarras -->
<script>
    var msg = document.getElementById('mensaje');
    setTimeout(function(){
        if (typeof(msg) != 'undefined' && msg != null){
            msg.remove();
        }
    },3000)
</script>
{% endblock %}

formularios/templates/formularios/prueba_models.html
{% extends "base.html" %}

{% block contenidos %}
        {% for guitarra in guitarras %}

           <h3>  {{guitarra.marca}} | {{guitarra.modelo}} | {{guitarra.cuerdas}}
                | {{guitarra.fecha_compra}}</h3> 
            

        {% endfor %}
<hr>
        {% for guitarra in guitarras_values %}

          <h3>  {{guitarra.marca}} | {{guitarra.modelo}} | {{guitarra.cuerdas}}
                | {{guitarra.fecha_compra}}</h3> 

        {% endfor %}


{% endblock %}